### ISSUE TITLE
Installation instructions 

### ISSUE THREAD

**Issue by ZompaSenior** [ConoscereLinux/asso-django#1]
@giobber it could be great if you can provide some instructions on how to use your installation system, if you think it could be the main way to perform.
Otherwise we can collect together some instructions for a more general way.

**Comment by giobber** [comment]
Yay I forgot to write instructions in README.md

**Comment by giobber** [comment]
Add instruction to install and run in 9bb28074471207bb968494396511a6c7df9a4dfe

**Comment by ZompaSenior** [comment]
Good job, but what about versions?

I suggest to work on Python 3.10 and Django 3.2, that is the LTS version ([Download Django](https://www.djangoproject.com/download/)).

I'm going to add versione to `requirements.txt`, is it ok?

**Comment by giobber** [comment]
I was unaware of the existance of the LTS version of Django, actually im using the 4.x version

**Comment by ZompaSenior** [comment]
LTS is supported until first quarter of 2024, actual 4.2 until the end of 2023.
For a project of this type, I prefer looking for a safer version, than can grant safety fix for more time (not so much difference by now).
At the end of next year is going to arrive the 4.3 LTS (supported until 2026), and we can switch on it.
It depends on the fact if we think we can go in production next year...
